stages:
  - test
  - build

test:
  stage: test
  image: smmccabe/docker
  script:
    - yarn install
    - yarn test

build:
  stage: build
  image: node:10-jessie
  artifacts:
    paths:
      - commercebot-linux
      - commercebot-macos
      - commercebot-win.exe
  script:
    - yarn install
    - yarn build